### ISSUE TITLE
Changing Reference value of objects

### ISSUE THREAD

**Issue by olbrichj** [tuist/xcodeproj#265]
I'm currently looking into xcodeproj whether I can just change a file reference and it will be updated throughout the project. Just changing the value doesn't lead to much success, as it doesn't change any objects referencing to it.

The usecase itself is to update all references within an Xcode Project so merges etc will be easier.

Is this possible with xcodeproj?

**Comment by pepibumur** [comment]
Changing the values of references is not supported. When a project is parsed, a reference instance is created for each of the objects whose value is hidden from you. If you create new objects, those get a temporary reference that gets fixed when the project is persisted. 

Could describe more that use case that you talk about?

**Comment by olbrichj** [comment]
I'm working with multiple teams on one project. All of them merge their changes (to the project file) to the master branch at any time. So we spend quite a lot of time merging project files (including fixing them). One tool we found is https://github.com/truebit/xUnique which is not actively developed anymore. 

To reduce this overhead I'm trying to create multiple tools which make either the merge easier (by creating deterministic identifiers within the project and sorting the references) or fixing the project (like xclint).

At the moment we are unable to use something like: https://github.com/yonaskolb/XcodeGen

**Comment by pepibumur** [comment]
We're finishing a new xcodeproj release that will generate deterministic references when generating objects in a project. However, the it doesn't allow you define your custom deterministic strategy to be applied to the objects that already exist in a project that you read.

Something that we could add support for, and that will help you solve that problem, is invalidating the references of your project objects, so that when you write it, they get generated deterministically.

I'll keep this issue open to tackle it before the next release. If you would like to open a PR and add it yourself your're welcome to do it.

**Comment by olbrichj** [comment]
Great!

**Comment by pepibumur** [comment]
I forgot to update you on this but there's already a method available in the latest version for invalidating the objects references: https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/PBXObjects.swift#L68

If you call that method and then save the project, it'll invalidate the references and generate new ones deterministically.
