### ISSUE TITLE
No way to set TargetAttributes

### ISSUE THREAD

**Issue by yonaskolb** [tuist/xcodeproj#288]
`PBXProject.attributes` is a `[String: Any]`.
One of the important attributes is `TargetAttributes` which is a map of the target UUID to special properties including, but not limited to `TestTargetID`, `ProvisioningStyle` and `DevelopmentTeam`.

Now that `PBXTarget.reference` is a `PBXObjectReference` in 5.0 we can't create that map anymore. If `PBXObjectReference.value` was public it would be possible to get the actual reference, but then it would have to be `fixed` before being set on the attributes.

Another option would be to have a typed `targetAttributes: [PBXObjectReference: [String: Any]]` property, that gets resolved and then gets merged with the other `attributes` on write

**Comment by pepibumur** [comment]
Good catch. Are the keys of `targetAttributes` always references to targets? If so, we can use `PBXObjectReference` as you suggested and update the writing logic to take the value. 

I wouldn't make the property `PBXObjectReference.value` because I think that's an internal detail the consumers of the API shouldn't worry about.

**Comment by yonaskolb** [comment]
Yeah I don't think the keys can be anything other than PBX references

**Comment by pepibumur** [comment]
Cool, then let's do it the way you suggested.
