### ISSUE TITLE
Why no CocoaPods or Carthage?

### ISSUE THREAD

**Issue by ileitch** [tuist/xcodeproj#301]
I was using xcproj previously, both with the SPM and CocoaPods. I'm quite disappointed to see no CocoaPods support in this fork. What's the rationale? It's not much effort to support CocoaPods.

**Comment by ileitch** [comment]
The reason I want to use CocoaPods is that SPM Xcode project generation sucks. At the moment I'm happy to maintain dependencies in both CocoaPods for day-to-day development and SPM for building releases.

**Comment by pepibumur** [comment]
Hi @ileitch. Thanks for reporting this. Answering your comments:

> What's the rationale? It's not much effort to support CocoaPods.

The new version depends on some frameworks from the Swift Package Manager, which unfortunately, don't have support for those dependency managers. Adding support for them would require adding a `.podspec` and make Carthage compatible the SPM project, which we obviously can't. 

> The reason I want to use CocoaPods is that SPM Xcode project generation sucks. At the moment I'm happy to maintain dependencies in both CocoaPods for day-to-day development and SPM for building releases.

Your concern is totally valid. However, I doubt we can bring that support that. What we could do instead is including a statically compiled library that you can pull and use in your projects. I can't prioritise this at the moment but you are welcome to contribute to the project. Other developers with a similar concern might benefit from that addition.

**Comment by ileitch** [comment]
It looks like the only dependency which doesn't support CocoaPods is the SPM itself, which appears to be used mostly just for its filesystem helpers. Would you consider using https://github.com/kylef/PathKit instead? I've used  it in my projects and have been very happy with it.

In general though, you're likely alienating a large set of potential users by not supporting CocoaPods.

**Comment by ileitch** [comment]
Some other options:
https://github.com/JohnSundell/Files
https://github.com/kareman/FileSmith

**Comment by pepibumur** [comment]
> It looks like the only dependency which doesn't support CocoaPods is the SPM itself, which appears to be used mostly just for its filesystem helpers. Would you consider using https://github.com/kylef/PathKit instead? I've used it in my projects and have been very happy with it.

You are right, but also for defining the CLI interface. We made the decision of using SPM instead for two main reasons:
- It's actively supported by Apple because it's needed by the SPM.
- We depend on one dependency instead of multiple.

I'm not against reconsidering this approach if it turns to be very cumbersome. Generating a static library is, in my opinion, another valid approach which one could also take in a couple of steps.

I can't prioritise this now but I'm happy to support/guide you or anyone interested in moving this proposal forward. I'm also curious to know if this is a shared feeling among the users of the library.

**Comment by ileitch** [comment]
I've made the switch to pure SPM 💯
