### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by ruipfcosta** [tuist/xcodeproj#312]
## Context 🕵️‍♀️
Although most of the types contain code level documentation, I feel the learning curve of xcodeproj is quite steep given the lack of documentation and examples. 

## What 🌱
I'm exploring xcodeproj on a personal project and my approach is simply based on trial and error, which involves having to inspect the resulting project file when things don't work as expected. Even tasks as simple as adding a new group to an existing project took some time and investigation to find out how to accomplish it. Some of the existing APIs also imply there may be different/related ways to perform the same task but where the outcome is in fact different.

## Proposal 🎉
I suggest adding a wiki where the different types (targets, build configurations, groups, files, etc) are introduced and followed by examples on out they can be manipulated. Dependencies between the different types should also be highlighted.
As an initial step I suggest creating at least an index page giving structure to the documentation, if necessary leaving the sections incomplete so people can contribute with examples later. Additionally a demo project can also be added the project.

By the way, I'm more than happy to work on this provided I get some support.

**Comment by pepibumur** [comment]
Hi @ruipfcosta 
Thanks for bringing this up. Documentation is something we haven't worked a lot on. As you mentioned, we added basic documentation to the attributes and method but not enough to understand  Xcode projects and how to manipulate them.

I like the idea of improving it in order to make Xcode projects and the library more accessible to anyone. xcodeproj opens a new API that developers might end up not using because of the steep learning curve. Since I doubt Apple will offer any documentation about the format, it's a good opportunity for us to step in and do some work.

I don't have much time these days to work on this but I'm happy to support you on the work. What if we start with what you suggested, documenting different types with a simple usage example, and we move from there?

Another thing that I had in mind but that I haven't worked on is writing a blog post to show all kinds of things you can do by accessing Xcode projects:
- Detecting missing files.
- Finding out duplicated build files
- ...

**Comment by ruipfcosta** [comment]
Hi @pepibumur, thanks for being open to improvements and for volunteering to provide some support!
As a first step towards documenting the project I'm suggesting some improvements to the README file on this [pull request](https://github.com/tuist/xcodeproj/pull/313).
My idea is to include a table of contents which later can point to the documentation pages as they become available.

Thanks!

**Comment by pepibumur** [comment]
> My idea is to include a table of contents which later can point to the documentation pages as they become available.

That's a great idea to start from. I've already approved and merged your PR. Feel free to take ownership in the documentation.

Also, it's worth mentioning that while you interact with the library, you might come up with ideas to make the interface of objects more convenient. Don't hesitate to propose improvements to abstract consumers of the API from the internals.

**Comment by pepibumur** [comment]
Closing this one in favor of https://github.com/tuist/xcodeproj/issues/382
