### ISSUE TITLE
[Question] how to add en embed binary (framework) ?

### ISSUE THREAD

**Issue by jpsarda** [tuist/xcodeproj#349]
## Context 🕵️‍♀️
It's not an issue, I'm trying to understand what is possible to do with xcodeproj.
I have a project with MANY targets (more than 100). Sometimes I create a new framework, and I need to embed the framework by hand on all targets,. It takes dozens of minutes.
Illustration :
[https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-EMBED_IN_APP_SECTION](url)
![tn2435_embedded_binary_list](https://user-images.githubusercontent.com/517839/49338678-fb4a3480-f624-11e8-836c-1ebd78c3a815.png)

## What 🌱
So would it be possible to add an embed binary to all targets by script with xcodeproj ?
Is there a small exemple or tutorial showing how to use xcodeproj ?

**Comment by pepibumur** [comment]
Hey @jpsarda. Thanks for bringing this up. Unfortunately, we haven't done much work in documenting common use cases of `xcodeproj`. In fact, I have planned to write a blog post with some examples that show how to use xcodeproj and how Xcode projects are structured.

Answering your question. Yes, it's possible to do everything that you can do with Xcode, but you need to understand a bit of the structure. Here's how you can achieve that:

- [Read](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Project/XcodeProj.swift#L19) the project with `xcodeproj`.
- You can find the copy binaries build phase by traversing the [copyBuildPhases](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Project/PBXProj.swift#L109) attribute and finding the one that copies the files into the [frameworks](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/BuildPhase/PBXCopyFilesBuildPhase.swift#L25) directory.
- The build phase has a files attribute. You can add your embedded frameworks there. To do so, you need to create a [PBXBuildFile](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/BuildPhase/PBXBuildFile.swift) that references the framework [file reference](https://github.com/tuist/xcodeproj/blob/master/Sources/xcodeproj/Objects/Files/PBXFileReference.swift).

I recommend you doing it by hand and checking the git diff. That'll tell you what exactly needs to be added and modified in the project, and you'll have to implement it using Swift and the xcodeproj library. Also, have a look at [this method](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/LinkGenerator.swift#L94) because it does exactly what you are trying to do.

**Comment by jpsarda** [comment]
Thank you, very helpful indeed. How can I be notified of your blog post ? I'm interested in an hello world example. I'm not sure yet how to use the tool, it's swift based but it's to be used in scripting mode and not to be used in Xcode, right ?

**Comment by pepibumur** [comment]
Exactly, you need to implement your own command line tool that makes use of the library. You can follow the [Tuist blog](https://tuist.io). I plan to write it on Christmas.

**Comment by pepibumur** [comment]
Hey @jpsarda. Apologies for taking me longer than expected to write something up. Here's the blog post https://ppinera.es/2019/03/15/xcodeproj/ . I hope it helps you better understand how Xcode projects are structured.
For the next major version we plan to add more documentation around it.
