### ISSUE TITLE
Indent can be improved

### ISSUE THREAD

**Issue by mengxiangyue** [tuist/xcodeproj#385]
## Context 🕵️‍♀️
the sections content between `/* Begin XXX section */` and `/* End PBXBuildFile section */` dont have tab after modifying it to write into `project.pbxproj`. So causes many diffs in git.

## Proposal 🎉
I learn it, and find you create new `var tmpStateHolder = StateHolder()` and dont set the `indent` property in `PBXProjEncoder.swift` (line 323). It works well after i set the value 2 `tmpStateHolder.indent = 2`.
could you check it and add it into the project if i correct.

**Comment by mengxiangyue** [comment]
you can try it by using `https://github.com/mengxiangyue/TestFramework`, then you can run the `command-tool` project, then you will get these below diffs:
![image](https://user-images.githubusercontent.com/1563329/53872436-39e2f700-4039-11e9-9e50-c28fac1f9bc3.png)

**Comment by mxcl** [comment]
I’ve been seeing this too, sorry for the lack of a report, it didn’t occur to me that it was a bug for some reason.

**Comment by Dschee** [comment]
I'm seeing this exact same issue in [this tool](https://github.com/JamitLabs/Accio) I'm working on right now. Would be great if this got fixed soon!

**Comment by pepibumur** [comment]
Found the issue. I've started fixing it on [this PR](https://github.com/tuist/xcodeproj/pull/391). Thanks to the test that I added I found out that there are issues with schemes and workspaces as well. I'll fix all of them and then merge the branch.

**Comment by pepibumur** [comment]
By the way, really cool idea @Dschee. Happy to see xcodeproj helping you making it real 😛

**Comment by Dschee** [comment]
Yes, it was much easier to accomplish thanks to xcodeproj. But there are two more things I noticed and I‘m not sure if these are tracked in issues yet (I could open them if not):

1. The xcodeproj generated identifiers when I add new files or geoups in my projects are longer than the ones generated by Xcode itself (32 vs 24). Why is that?

2. Why doesn‘t the project adhere to the community standard of using uppercased camel casing for the project name? It looks really weird to me to „import xcodeproj“ instead of say „import XcodeProj“.

**Comment by pepibumur** [comment]
> 1. The xcodeproj generated identifiers when I add new files or groups in my projects are longer than the ones generated by Xcode itself (32 vs 24). Why is that?

We [are using md5](https://github.com/tuist/xcodeproj/blob/2b1c9bafb5cc4c39c61de740c916b7676b17be9d/Sources/xcodeproj/Utils/ReferenceGenerator.swift#L298) which generates 32 characters. Would you mind opening an issue for this one?

> Why doesn‘t the project adhere to the community standard of using uppercased camel casing for the project name? It looks really weird to me to import xcodeproj instead of say import XcodeProj.

There's no real reason for it. We set `xcodeproj` as a name and sticked to that. I personally don't think it's a big deal. If you believe the opposite, feel free to open an issue and let's hear what other contributors think about it. If they agree, I think it's fine renaming it. We'd need to wait though for a major release because this would be a breaking change.

**Comment by Dschee** [comment]
@pepibumur Thank you for your answer. I just opened #392 and #393 to track both issues.

**Comment by pepibumur** [comment]
Thanks @Dschee very appreciated 🙏
